"""Link translated translation units and emit Cool declarations and initialization."""
import re
from pathlib import Path
from ctype_model import CError


def emit(p, args):
    names = {}
    for key in list(p.funcs) + list(p.globals):
        names[key] = p.cool_ident((key[0] + '_' if key[0] else '') + key[1])
    def fix(s):
        s = re.sub('\x01([^\x02]*)\x02([^\x03]*)\x03',
                   lambda m: names[(m[1], m[2])], s)
        s = re.sub('\x04([^\x05]*)\x05', lambda m: m[1], s)
        # File-level identifiers are renamed outside string literals only.
        renames = {k[1]: v for k, v in names.items() if not k[0] and k[1] != v}
        return re.sub(r'"(?:\\.|[^"\\])*"|\b[A-Za-z_]\w*\b',
                      lambda m: renames.get(m[0], m[0]), s)
    refs = {('f', k): r for k, _, r in p.func_defs}
    refs.update({('g', k): r for k, _, r, _ in p.inits})
    if args.roots:
        keep = set()
        pending = [('f', ('', n)) for n in args.roots]
        while pending:
            x = pending.pop()
            if x in keep: continue
            keep.add(x)
            pending.extend(refs.get(x, ()))
    else:
        keep = {('f', k) for k in p.funcs} | {('g', k) for k in p.globals}
    out = ['// Generated by tools/c2hc; do not edit.']
    libc = args.libc or str(Path(__file__).resolve().parents[2] / 'coolc/LibC/LibC.cool')
    out.append(f'#include "{libc}"')
    libc_names = set(re.findall(r'^\w+[\w *]*?\b(\w+)\s*\(', (Path(__file__).resolve().parents[2] / 'coolc/LibC/LibC.cool').read_text(), re.M))
    out += ['F64 C2HUnsignedToFloat(U64i x) {F64 f = x & 0x7FFFFFFFFFFFFFFF; if (x >> 63) f += 9223372036854775808.0; return f;}',
            'U64i C2HFloatToUnsigned(F64 x) {I64i n; if (x >= 9223372036854775808.0) {n = x - 9223372036854775808.0; return n(U64i) | 0x8000000000000000;} n = x; return n(U64i);}']
    # Forward class declarations allow mutually recursive pointer fields.
    out += ['extern class ' + r.cool + ';' for r in p.recs if not r.external]
    out += [p.record_text(r) for r in p.recs if not r.external]
    for k in p.global_order:
        g = p.globals[k]
        if ('g', k) in keep and not g.external:
            out.append(p.decl(g.ct, names[k]) + ';')
    def signature(ft, name):
        params = [p.decl(t, f'_p{i}') for i, t in enumerate(ft.params)]
        if ft.variadic: params.append('...')
        return p.cool(ft.to) + ' ' + name + '(' + ', '.join(params) + ')'
    for k, f in p.funcs.items():
        if ('f', k) in keep and not f['external'] and (f['defined'] or k[1] not in libc_names):
            out.append(('extern ' if f['defined'] else 'import ') + signature(f['ct'], names[k]) + ';')
    for ft, name in p.thunks.values():
        params = [p.decl(t, f'_p{i}') for i, t in enumerate(ft.params)]
        decl = p.cool(ft.to) + ' (*fn)(' + ', '.join(params) + ');'
        out.append(p.cool(ft.to) + ' ' + name + '(U8i *fp' + (', ' if params else '') + ', '.join(params) + ') {\n    ' + decl + '\n    fn = fp;\n    ' + ('return ' if ft.to.kind != 'void' else '') + '(*fn)(' + ', '.join(f'_p{i}' for i in range(len(params))) + ');\n}')
    out += [fix(s) for k, s, _ in p.func_defs if ('f', k) in keep]
    for i, (k, lines, _, decls) in enumerate(p.inits):
        if ('g', k) not in keep: continue
        out.append(f'U0 _c2hc_init_{i}() {{')
        for t, n in decls:
            out.append('    ' + (p.decl(t, n) if not isinstance(t, str) else t + ' ' + n) + ';')
        out += [fix(s) for s in lines]
        out += ['}', f'_c2hc_init_{i}();']
    if not args.library and not args.roots and ('', 'main') in p.funcs:
        ft = p.funcs[('', 'main')]['ct']
        call = 'main(' + (', '.join(['LibCArgc()', 'LibCArgv()'][:len(ft.params)])) + ')'
        out.append('exit(' + call + ');')
    return '\n\n'.join(out) + '\n'
