#!/usr/bin/env python3
# Make the Aiwnios frontend's backend switchable between the C backend and
# the CoolC port at run time. For every `import ... __HC_X(...)` in
# AIWNIOS_CodeGen.HC, emit a wrapper HCSel_X that calls the port's __PB_X
# when b_use_port is set and the C runtime's __HC_X otherwise, and point the
# frontend's calls at the wrappers.
# Usage: mkswitch.py <copy of AIWNIOS_CodeGen.HC> <out Switch.HC>
import re, sys
cg_path, out_path = sys.argv[1], sys.argv[2]
cg = open(cg_path, 'rb').read().decode('latin-1')

def split_params(p):
    out, depth, cur = [], 0, ''
    for ch in p:
        if ch == '(': depth += 1
        if ch == ')': depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur); cur = ''
        else:
            cur += ch
    if cur.strip(): out.append(cur)
    return [x.strip() for x in out]

decls = {}
for m in re.finditer(r'^import\s+(\w+)\s*(\**)\s*(__HC_\w+)\s*\((.*)\)\s*;', cg, re.M):
    ret, stars, name, params = m.group(1), m.group(2), m.group(3), m.group(4)
    decls.setdefault(name, (ret + (' ' + stars if stars else ''), params))

# Called by the frontend but declared elsewhere (KernelA.HH), not imported here.
decls.setdefault('__HC_CmpCtrl_SetAOT', ('U0', 'U8 *'))

w = ['// Generated by tools/porttest/mkswitch.py: frontend -> C backend or CoolC port.',
     'I64 b_use_port;', '']
for name, (ret, params) in decls.items():
    ps, args = [], []
    for k, p in enumerate(split_params(params)):
        dflt = ''
        if '=' in p and '(*' not in p:
            p, dflt = p.split('=', 1); dflt = '=' + dflt.strip(); p = p.strip()
        if '(*' in p:
            typ = 'U8 *'
        else:
            mm = re.match(r'^(\w+)\s*(\**)\s*(\w+)?$', p)
            typ = mm.group(1) + (' ' + mm.group(2) if mm.group(2) else '')
        ps.append(f'{typ} a{k}{dflt}'); args.append(f'a{k}')
    sel = 'HCSel' + name[4:]
    call = ','.join(args)
    body = (f'  if (b_use_port)\n    return __PB{name[4:]}({call});\n  return {name}({call});'
            if ret.strip() != 'U0' else
            f'  if (b_use_port)\n    __PB{name[4:]}({call});\n  else\n    {name}({call});')
    w.append(f'{ret} {sel}({",".join(ps)})\n{{\n{body}\n}}\n')
open(out_path, 'w').write('\n'.join(w))

# Point calls after the declaration block at the wrappers.
i = cg.index('#endif', cg.index('#ifdef IMPORT_AIWNIOS_SYMS')) + 6
head, body = cg[:i], cg[i:]
body = re.sub(r'(?<![\w])__HC_(\w+)\s*\(', lambda m: f'HCSel_{m.group(1)}(' if '__HC_' + m.group(1) in decls else m.group(0), body)
# Include the port files with explicit Port/ paths: during the bootstrap's
# second stage #include resolves against the current directory, not the
# including file's.
import os
bk = open(os.path.join(os.path.dirname(cg_path), 'Port', 'Backend.HC')).read()
incs = ''.join(f'#include "Port/{f}"\n' for f in re.findall(r'^#include "([^"]+)"', bk, re.M))
head += '\n#define BACKEND_HOSTED\n' + incs + '#include "Port/Switch.HC"\n'
open(cg_path, 'wb').write((head + body).encode('latin-1'))
print(f'{len(decls)} wrappers')
