name = "Cool"
grammar = "holyc"
path_suffixes = ["cool", "coolh", "HC", "HH", "hc", "hh"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = ";:.,=}])>"
tab_size = 4
hard_tabs = false
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
