#!/usr/bin/env python3
"""Select the COOLCOM_KERNEL branches of the canonical header, without decoding.

All layouts, declarations and platform differences belong in
coolc/Frontend/KernelA.coolh. Other preprocessor conditions (TARGET_AARCH64,
IMPORT_AIWNIOS_SYMS, etc.) stay verbatim for the Cool compiler to evaluate.
The generated OS header is also used by mkprelude and installed on the guest
for MakeKernel; neither consumer needs the host branches.
Usage: tools/mkkernela.py > os/Kernel/KernelA.coolh (normally run by make)
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "coolc/Frontend/KernelA.coolh"
DIRECTIVE = re.compile(rb"^[ \t]*#[ \t]*(ifdef|ifndef|if|elif|else|endif)\b(.*)")


def project(source, kernel=True):
    """Resolve only #ifdef/#ifndef COOLCOM_KERNEL; preserve all other bytes."""
    out, stack = [], []
    active = True
    for number, line in enumerate(source.splitlines(keepends=True), 1):
        match = DIRECTIVE.match(line)
        if match:
            op, arg = match.groups()
            arg = arg.split(b"//", 1)[0].strip()
            if op in (b"if", b"ifdef", b"ifndef"):
                selected = None
                if arg == b"COOLCOM_KERNEL" and op in (b"ifdef", b"ifndef"):
                    selected = kernel if op == b"ifdef" else not kernel
                elif b"COOLCOM_KERNEL" in arg:
                    raise ValueError(f"line {number}: use #ifdef/#ifndef COOLCOM_KERNEL")
                stack.append((active, selected, False))
                active = active and selected is not False
                if selected is not None:
                    continue
            elif op in (b"else", b"elif"):
                if not stack or stack[-1][2]:
                    raise ValueError(f"line {number}: unexpected #{op.decode('ascii')}")
                parent, selected, _ = stack[-1]
                if selected is not None:
                    if op == b"elif":
                        raise ValueError(f"line {number}: use #else for COOLCOM_KERNEL")
                    active = parent and not selected
                stack[-1] = (parent, selected, op == b"else")
                if selected is not None:
                    continue
            elif op == b"endif":
                if not stack:
                    raise ValueError(f"line {number}: unexpected #endif")
                active, selected, _ = stack.pop()
                if selected is not None:
                    continue
        if active:
            out.append(line)
    if stack:
        raise ValueError("unterminated preprocessor condition")
    return b"".join(out)


def main():
    try:
        header = project(SRC.read_bytes())
    except ValueError as error:
        sys.exit(f"mkkernela: {error}")
    sys.stdout.buffer.write(
        b"// Generated by tools/mkkernela.py; edit coolc/Frontend/KernelA.coolh.\n"
        + header
    )


if __name__ == "__main__":
    main()
