#!/usr/bin/env python3
"""Make os/Kernel/KernelA.HH, the kernel's TempleOS header, from the compiler's
copy coolc/Frontend/KernelA.HH (Aiwnios Src/KernelA.HH, e155e87).

Kept: #defines, unions, classes and the `extern` forward declarations (a
kernel definition may differ from its TempleOS prototype; an extern nothing
defines fails at link time only if it is used).
Dropped: `import`s (Aiwnios host functions, which don't exist here) and the
classes the kernel lays out itself (CTask, CCPU, its heap), plus CSysFixedArea
which embeds them. Kernel-specific additions go in KERNEL_TAIL.
Usage: tools/mkkernela.py > os/Kernel/KernelA.HH
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "coolc/Frontend/KernelA.HH"
DROP_CLASSES = {"CCPU", "CHeapCtrl", "CMemBlk", "CSysFixedArea"}

HEAD = """\
// The kernel's TempleOS header, generated by tools/mkkernela.py from
// coolc/Frontend/KernelA.HH (translated from Aiwnios Src/KernelA.HH,
// nrootconauto, BSD-3, commit e155e87; TempleOS by Terry A. Davis, public
// domain). No imports; the kernel owns CCPU and its
// heap (MultiCore.HC, Mem.HC). Do not edit; edit the script.
extern class CMemBlk;
"""

KERNEL_TAIL = """
// ---- coolcom kernel additions ----
#define BDT_VIRTIO 7 // coolvm virtio-blk (Blk.HC)
#define BDT_TYPES_NUM 8
"""


def main():
    lines = SRC.read_bytes().decode("latin-1").split("\n")
    out, i = [], 0
    decl = re.compile(r"^\s*(public\s+)?(import|_import)\b")
    cls = re.compile(r"^\s*(public\s+)?class\s+(\w+)")
    while i < len(lines):
        ln = lines[i]
        m = cls.match(ln)
        if m and m.group(2) in DROP_CLASSES and not ln.rstrip().endswith(";"):
            depth, seen = 0, False
            while i < len(lines):
                depth += lines[i].count("{") - lines[i].count("}")
                seen = seen or "{" in lines[i]
                i += 1
                if seen and depth == 0:
                    break
            continue
        if decl.match(ln) or ln.startswith('#include "Headers.HH"'):  # (compiler prototypes)
            while i < len(lines) and ";" not in lines[i]:
                i += 1
            i += 1
            continue
        out.append(ln)
        i += 1
    out = [ln.replace("I64 user_data, user_data2, is_single_step;",
                      "I64 user_data, user_data2, is_single_step;\n    U8 *stack_alloc, *stack_guard, *stack_end;") for ln in out]
    text = re.sub(r"\n\n\n+", "\n\n", HEAD + "\n".join(out) + KERNEL_TAIL)  # (as hcfmt does)
    text = text.replace("I64 user_data, user_data2, is_single_step;", "I64 user_data, user_data2, is_single_step;\n    U8 *terminal, *shell_ctx, *key_history, *bin_module;")
    sys.stdout.buffer.write(text.encode("latin-1"))


main()
