#!/usr/bin/env python3
"""Make the shell prelude from the kernel sources (os/Kernel/Kernel.HC and
what it #includes, in order).

The shell JIT-compiles the prelude before the first command line. It holds
the kernel's #defines, classes and unions verbatim, and an `extern` prototype
for every function the kernel defines (assembly `import`s become `extern`
too). In JIT mode `extern` binds a prototype to the system symbol of the same
name, and the shell registers every kernel symbol as one (Shell.HC, from the
table tools/binlink.py puts in the Image), so shell code calls the kernel
directly. Global variables and function bodies are left out.
Usage: mkprelude.py os/Kernel/Kernel.HC > build/ShellPrelude.HH
"""
import pathlib
import re
import sys


def strip_comments(text):
    """Replace comments with spaces, keeping strings, chars and line breaks."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if c in "\"'":
            j = i + 1
            while j < n and text[j] != c:
                j += 2 if text[j] == "\\" else 1
            out.append(text[i:j + 1])
            i = j + 1
        elif text.startswith("//", i):
            j = text.find("\n", i)
            j = n if j < 0 else j
            i = j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            j = n if j < 0 else j + 2
            out.append(re.sub(r"[^\n]", " ", text[i:j]))
            i = j
        else:
            out.append(c)
            i += 1
    return "".join(out)


def braces(s):
    """Net brace count of s, ignoring strings and char constants."""
    d, i, n = 0, 0, len(s)
    while i < n:
        c = s[i]
        if c in "\"'":
            j = i + 1
            while j < n and s[j] != c:
                j += 2 if s[j] == "\\" else 1
            i = j + 1
            continue
        d += (c == "{") - (c == "}")
        i += 1
    return d


def first_brace(s):
    i, n = 0, len(s)
    while i < n:
        c = s[i]
        if c in "\"'":
            j = i + 1
            while j < n and s[j] != c:
                j += 2 if s[j] == "\\" else 1
            i = j + 1
            continue
        if c == "{":
            return i
        i += 1
    return -1


def process(path, out):
    text = strip_comments(path.read_bytes().decode("latin-1"))
    lines = text.split("\n")
    i = 0
    stmt = ""
    while i < len(lines):
        ln = lines[i]
        i += 1
        if not stmt:
            s = ln.strip()
            if not s:
                continue
            if s.startswith("#"):
                block = [ln]
                while block[-1].rstrip().endswith("\\") and i < len(lines):
                    block.append(lines[i])
                    i += 1
                if not s.startswith("#include"):
                    out.append("\n".join(block))
                continue
        stmt += ln + "\n"
        b = first_brace(stmt)
        if b < 0:
            if ";" in stmt:
                emit_decl(stmt, out)
                stmt = ""
            continue
        # A braced statement: read to its closing brace (and the ';' after a class).
        while braces(stmt) > 0 and i < len(lines):
            stmt += lines[i] + "\n"
            i += 1
        head = stmt[:b]
        if re.match(r"\s*(public\s+)?(\w+\s+)?(class|union)\b", head) and "(" not in head:
            while not stmt.rstrip().endswith(";") and i < len(lines):
                stmt += lines[i] + "\n"
                i += 1
            out.append(stmt.rstrip())
        elif head.rstrip().endswith(")") and "=" not in head.split("(")[0]:
            out.append("extern " + " ".join(head.split()) + ";")
        stmt = ""


def emit_decl(stmt, out):
    s = " ".join(stmt.split())
    if re.match(r"(extern|import)\s+class\b", s):
        out.append(s)
    elif s.startswith("import "):
        out.append("extern " + s[len("import "):])


def main():
    entry = pathlib.Path(sys.argv[1])
    out = ["// Shell prelude, generated by tools/mkprelude.py from the kernel sources."]
    for m in re.finditer(r'^#include\s+"([^"]+)"', entry.read_text(errors="replace"), re.M):
        f = entry.parent / m.group(1)
        out.append(f"// ---- {m.group(1)} ----")
        process(f, out)
    sys.stdout.buffer.write(("\n".join(out) + "\n").encode("latin-1"))


main()
