(* HolyC runtime. Aggregate results use explicit output pointers. *)
let source = {|
#define U8 U8i
#define I8 I8i
#define U16 U16i
#define I16 I16i
#define U32 U32i
#define I32 I32i
#define U64 U64i
#define I64 I64i
// Generated by Warm. Classes are packed; the ABI is private to this module.
#ifndef WARM_KERNEL
import U0 Print(U8 *fmt, ...);
import U8 *MAlloc(I64 size);
import U8 *CAlloc(I64 size);
import U0 Free(U8 *ptr);
import U8 *MemCpy(U8 *dst, U8 *src, I64 size);
import U8 *MemSet(U8 *dst, I64 value, I64 size);
import U0 NativeExit(I64 status);
import U0 NativeErrPutS(U8 *text);
import I64 NativeArgCount();
import U8 *NativeArg(I64 index);
import I64 StrLen(U8 *text);
#else
U0 NativeErrPutS(U8 *text) { PutS(text); }
I64 NativeArgCount() { return 0; }
U8 *NativeArg(I64 index) { return NULL; }
#endif
class au_span_t { U8 *wh_data; U64 wh_size; };
I32 putchar(U8 c) { Print("%c", c); return c; }
I32 puts(U8 *s) { Print("%s\n", s); return 0; }
U0 wh_abort(U8 *message) {
    NativeErrPutS(message);
    NativeErrPutS("\n");
    NativeExit(255);
}
U8 au_abort(au_span_t *message) { wh_abort(message->wh_data); return 0; }
U0 au_make_span(au_span_t *out, U8 *data, U64 size) {
    out->wh_data = data; out->wh_size = size;
}
U0 au_make_span_from_string(au_span_t *out, U8 *data, U64 size) {
    au_make_span(out, data, size);
}
U64 au_get_argc() { return NativeArgCount(); }
U0 au_get_nth_arg(au_span_t *out, U64 n) {
    U8 *arg = NativeArg(n);
    if (!arg) wh_abort("Command line argument access out of bounds.");
    U64 len = StrLen(arg);
    if (len > 10240) wh_abort("Command line argument exceeds maximum length of 10 kibibytes.");
    au_make_span(out, arg, len);
}
U8 *au_array_index(au_span_t *sp, U64 index, U64 size) {
    if (index >= sp->wh_size) wh_abort("Array index out of bounds.");
    if (size && (index > (0xffffffffffffffff / size)))
        wh_abort("Multiplication overflow in array indexing operation.");
    return sp->wh_data + (index * size);
}
// A private size header allows realloc without depending on host heap metadata.
U8 *au_calloc(U64 size, U64 count) {
    U64 total = size * count;
    if (size && (count > ((0x7fffffffffffffff - 8) / size))) return 0;
    U64 *p = CAlloc(total + 8);
    if (!p) return 0;
    *p = total;
    return p(U8 *) + 8;
}
U8 au_free(U8 *p) { if (p) Free(p - 8); return 0; }
U8 *au_realloc(U8 *p, U64 size) {
    U8 *q = au_calloc(size, 1);
    U64 n;
    if (!q) return 0;
    if (p) {
        n = *(p - 8)(U64 *);
        if (size < n) n = size;
        MemCpy(q, p, n);
        au_free(p);
    }
    return q;
}
U8 *au_memcpy(U8 *d, U8 *s, U64 n) { MemCpy(d, s, n); return d; }
U8 *au_memmove(U8 *d, U8 *s, U64 n) {
    U64 i;
    if (d < s) { for (i = 0; i < n; i++) d[i] = s[i]; }
    else { i = n; while (i) { i--; d[i] = s[i]; } }
    return d;
}
|}
